---
namespace: shadowthrone99
name: localsystem
version: 1.0.0
readme: README.md
authors:
  - Peter Hall <pete.piper.hall@gmail.com>
description: >
  Bootstrap and configure a local Ubuntu 24.04 LTS workstation with
  developer tools, Google Cloud SDK, desktop utilities, security tooling,
  and virtualization support.
license:
  - MIT

tags:
  - ubuntu
  - workstation
  - desktop
  - gnome
  - google
  - cloud
  - kubernetes
  - security
  - virtualization

dependencies: [ ]

repository: https://github.com/Shadowthrone99/ansible-role-localsystem
issues: https://github.com/Shadowthrone99/ansible-role-localsystem/issues
documentation: https://github.com/Shadowthrone99/ansible-role-localsystem/blob/main/README.md
homepage: https://github.com/Shadowthrone99/ansible-role-localsystem

